name: Lint Code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./backend  # ✅ Correct path to package.json

      - name: Install ESLint
        run: npm install eslint --save-dev
        working-directory: ./backend

      - name: Run ESLint
        run: npx eslint .
        working-directory: ./backend  # ✅ Correct path to run ESLint
